"""Reads a returned associate .xlsx workbook (as generated by Associate
File Splitting) back into structured metadata + data rows for
Consolidation (PROJECT_SPEC.md section 19).

This is the read-side counterpart of ``infrastructure.xlsx_writer``: it
knows the same Metadata/Data sheet layout and nothing else.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from openpyxl import load_workbook

from operations_allocation.domain.exceptions import InvalidReturnedFileError


@dataclass(frozen=True, slots=True)
class ReturnedWorkbook:
    metadata: dict[str, str]
    headers: tuple[str, ...]
    rows: tuple[dict[str, str | None], ...]


def read_returned_workbook(path: Path | str) -> ReturnedWorkbook:
    workbook = load_workbook(filename=path, read_only=True, data_only=True)
    try:
        sheet_names = set(workbook.sheetnames)
        missing = {"Metadata", "Data"} - sheet_names
        if missing:
            raise InvalidReturnedFileError(
                f"'{Path(path).name}' is missing the {', '.join(sorted(missing))} sheet(s) expected in a "
                "distributed associate work file. Found sheets: "
                f"{', '.join(workbook.sheetnames) or '(none)'}. Make sure you are selecting the file that was "
                "generated by Distribution and returned by the associate, not the original source file."
            )
        metadata_sheet = workbook["Metadata"]
        metadata = {row[0]: row[1] for row in metadata_sheet.iter_rows(min_row=2, values_only=True) if row and row[0] is not None}

        data_sheet = workbook["Data"]
        rows_iterator = data_sheet.iter_rows(values_only=True)
        try:
            header_row = next(rows_iterator)
        except StopIteration:
            return ReturnedWorkbook(metadata=metadata, headers=(), rows=())
        headers = tuple(str(cell) if cell is not None else "" for cell in header_row)
        rows = tuple(
            {header: value for header, value in zip(headers, raw_row)}
            for raw_row in rows_iterator
            if any(cell is not None for cell in raw_row)
        )
    finally:
        workbook.close()
    return ReturnedWorkbook(metadata=metadata, headers=headers, rows=rows)
